# kubectl create secret generic dwh-secrets \
#   --from-literal=TOR_CONTROL_PASSWORD=your_password \
#   --from-literal=DWH_API_KEY=your_api_key \
#   -n deepwebharvester
apiVersion: v1
kind: Secret
metadata:
  name: dwh-secrets
  namespace: deepwebharvester
type: Opaque
stringData:
  TOR_CONTROL_PASSWORD: "REPLACE_ME"
  DWH_API_KEY: "REPLACE_ME"
